name = "supabase-cookie-auth-proxy"
type = "javascript"
zone_id = ""
account_id = ""
route = ""
workers_dev = true
compatibility_date = "2022-02-28"
kv_namespaces = [
	{ binding = "SESSIONS_KV", id = "" }
]

[vars]
SUPABASE_HOSTNAME = ""
SUPABASE_ANON_KEY = ""

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"
